services:
    menu_builder_event_listener:
        class: Jarr\MenuBuilderBundle\EventListener\MenuBuilderListener
        arguments:
            - '@twig'
            - '@menu_builder_factory'
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    menu_builder_factory:
        class: Jarr\MenuBuilderBundle\MenuBuilder\MenuBuilderFactory
        public: true
