services:
    Jarr\MenuBuilderBundle\EventListener\MenuBuilderListener:
        arguments: ['@twig']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    Jarr\MenuBuilderBundle\MenuBuilder\MenuBuilderFactory:
        public: true
