services:
    menu_builder_event_listener:
        class: RickWest\MenuBuilderBundle\EventListener\MenuBuilderListener
        arguments:
            - '@twig'
            - '@menu_builder_factory'
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    menu_builder_factory:
        class: RickWest\MenuBuilderBundle\MenuBuilder\MenuBuilderFactory
        public: true

#   By creating an alias, the autowiring subsystem knows that the @menu_builder_factory service should be injected
#   when dealing with the MenuBuilderFactoryInterface.
    RickWest\MenuBuilderBundle\MenuBuilder\MenuBuilderFactoryInterface: '@menu_builder_factory'